const dishes = [
  {
    title: "Mushroom Soup",

    ingredients: ["Musroom", "Onion", "Salt", "Garlic", "Flour"],

    cuisine: "Turkish",
    dishType: "soup",
    price: 12.5,
    image: "/images/soup_photos/mushroom_soup.jpg",
  },

  {
    title: "Pumpkin Soup",

    ingredients: [
      "Pumpkin",
      "Onion",
      "Salt",
      "Potatoes",
      "Garlic",
      "Fresh Parsley",
    ],

    cuisine: "Haiti",
    dishType: "soup",
    price: 12.5,
    image: "/images/soup_photos/pumpkin_soup.jpg",
  },
  {
    title: "Tomato Soup",

    ingredients: [
      "Butter",
      "Onion",
      "Sugar",
      "Whipping Cream",
      "Garlic",
      "Tomatoes",
      "Parmesan Cheese",
    ],

    cuisine: "Spain",
    dishType: "soup",
    price: 12.5,
    image: "/images/soup_photos/tomato_soup.jpg",
  },
  {
    title: "Vegetable Soup",

    ingredients: [
      "Butter",
      "Onion",
      "Sugar",
      "Whipping Cream",
      "Garlic",
      "Tomatoes",
      "Parmesan Cheese",
    ],

    cuisine: "Spain",
    dishType: "soup",
    price: 12.5,
    image: "/images/soup_photos/vegetable_soup.jpg",
  },

  {
    title: "Chicken Katsu Hero",
    ingredients: [
      "Chicken",
      "Onion",
      "Pickles",
      "Mayonnaise",
      "Egg",
      "Olive Oil",
    ],
    cuisine: "Japanese",
    dishType: "main_course",
    price: 22.75,
    image: "/images/main_course_photos/chicken-katsu-hero.jpg",
  },

  {
    title: "Lamb Chops Sizzled with Garlic",
    ingredients: [
      "lamp",
      "Onion",
      "Pepper",
      "Lemon Juice",
      "Parsley",
      "Olive Oil",
      "Red Pepper",
    ],
    cuisine: "Spain",
    dishType: "main_course",
    price: 24.5,
    image: "/images/main_course_photos/Lamb-Chops-Sizzled-with-Garlic.jpg",
  },
  {
    title: "Steak Horizo Potato Kabobs",
    ingredients: [
      "Chorizo slices",
      "Onion",
      "Potatoes",
      "Olive Oil",
      "Smoked Paprika",
      "Red Wine Vinegar",
    ],
    cuisine: "France",
    dishType: "main_course",
    price: 23.5,
    image: "/images/main_course_photos/steak_chorizo_potato_kabobs.jpg",
  },
  {
    title: "Steak Au Poivre Red Wine Pan Sauce Hero",
    ingredients: [
      "Rib Eye Steak",
      "Black Pepper",
      "Butter",
      "Minced Shallots",
      "Red Wine",
      "Beef Broth",
    ],
    cuisine: "France",
    dishType: "main_course",
    price: 22.5,
    image:
      "/images/main_course_photos/steak-au-poivre-red-wine-pan-sauce-hero.jpg",
  },

  {
    title: "Fettucine",
    ingredients: [
      "Fettuccine pasta",
      "Butter",
      "Havy cream",
      "Garlic Salt",
      "Romano Cheese",
      "Parmesan Cheese",
    ],
    cuisine: "Italy",
    dishType: "pasta",
    price: 19.5,
    image: "/images/pasta_photos/Fettucine.jpg",
  },

  {
    title: "Macoroni",
    ingredients: [
      "Elbow macaroni",
      "Butter",
      "Flour",
      "Salt",
      "Black Pepper",
      "Cheddar Cheese",
      "Milk",
    ],
    cuisine: "Italy",
    dishType: "pasta",
    price: 19.5,
    image: "/images/pasta_photos/macaroni.jpg",
  },

  {
    title: "Mozzarella Penne Rosa",
    ingredients: [
      "Dried Tomatoes",
      "Garlic",
      "Mushrooms",
      "Simmer Marina Sauce",
      "Mozzarella Cheese",
      "Spinach",
      "Basil",
    ],
    cuisine: "Italy",
    dishType: "pasta",
    price: 19.5,
    image: "/images/pasta_photos/Mozzarella_Penne_Rosa.jpg",
  },

  {
    title: "Ravioli",
    ingredients: [
      "Flour",
      "Sea Salt",
      "Freshly Grated Nutmeg",
      "Eggs",
      "Virgin Olive Oil",
    ],
    cuisine: "Italy",
    dishType: "pasta",
    price: 19.5,
    image: "/images/pasta_photos/Ravioli.jpg",
  },

  {
    title: "Neapolitan ",
    ingredients: ["Tomato sauce", "Mozzzarella cheese", "Semolina Flour"],
    cuisine: "Italy",
    dishType: "pizza",
    price: 17.0,
    image: "/images/pizza_photos/neapolitan-pizza.jpg",
  },

  {
    title: "Pepperoni",
    ingredients: [
      "Tomato Paste",
      "Dried Oregano",
      "Dried Basil",
      "Garlic Powder",
      "Onion Powder",
      "Black Pepper",
      "Sugar",
      "Salt",
    ],
    cuisine: "Italy",
    dishType: "pizza",
    price: 17.0,
    image: "/images/pizza_photos/pepperoni_pizza.jpg",
  },

  {
    title: "Margarita",
    ingredients: ["Tomato Paste", "Mozzarella Balls", "Olive Oil", "Salt"],
    cuisine: "Italy",
    dishType: "pizza",
    price: 17.0,
    image: "/images/pizza_photos/pizza-margarita.jpg",
  },

  {
    title: "Romana",
    ingredients: ["Dry Yeast", "Romana Flour", "Water", "Salt"],
    cuisine: "Italy",
    dishType: "pizza",
    price: 17.0,
    image: "/images/pizza_photos/pizza-romana.jpg",
  },
  {
    title: "Manti",
    ingredients: [
      "Egg",
      "Wheat Flour",
      "Water",
      "Salt",
      "Beef",
      "Yoghurt",
      "Garlic",
      "Red Pepper",
    ],
    cuisine: "Turkish",
    dishType: "snack",
    price: 19.0,
    image: "/images/snack_photos/manti.jpg",
  },

  {
    title: "Sarma",
    ingredients: [
      "Pickled Wine Leaves",
      "Rice",
      "Parsley",
      "Fresh Mint",
      "Onion",
      "Olive Oil",
      "Black Pepper",
    ],
    cuisine: "Turkish",
    dishType: "snack",
    price: 19.0,
    image: "/images/snack_photos/sarma.jpg",
  },

  {
    title: "Bluberry Pie",
    ingredients: [
      "Blueberries",
      "Ground Cinnamon",
      "Sugar",
      "Cornstarch",
      "Pie Crust",
      "Granulated Sugar",
      "Lemon Juice",
      "Butter",
      " Fresh Blueberries",
    ],
    cuisine: "The United Kingdom",
    dishType: "dessert",
    price: 19.0,
    image: "/images/dessert_photos/Blueberry-pie.jpeg",
  },

  {
    title: "Chocolate souffle",
    ingredients: [
      "Butter",
      "Sugar",
      "Milk",
      "Dark Chocolate",
      "Cocoa Powder",
      "Egg",
      "Vanilla Extract",
    ],
    cuisine: "France",
    dishType: "dessert",
    price: 19.0,
    image: "/images/dessert_photos/chocolate-souffle.jpg",
  },
  {
    title: "Tiramisu",
    ingredients: [
      "Cocoa Powder",
      "Sugar",
      "Ladyfingers",
      "Egg yolks",
      "Coffe",
      "Egg",
      "Vanilla Extract",
      "Mascarpone",
    ],
    cuisine: "Italy",
    dishType: "dessert",
    price: 19.0,
    image: "/images/dessert_photos/tiramisu.jpg",
  },
  {
    title: "Cabernet Sauvignon",
    ingredients: "Red Grapes",
    cuisine: "France",
    dishType: "drink",
    price: 24.0,
    image: "/images/drinks_photos/Cabernet-Sauvignon.jpeg",
  },
  {
    title: "Rose Sparkling",
    ingredients: "Red Grapes,Sugar,Yeast",
    cuisine: "Italy",
    dishType: "drink",
    price: 24.0,
    image: "/images/drinks_photos/Rose_Sparkling_Wine.jpeg",
  },

  {
    title: "Coca Cola",
    ingredients: "Not Available",
    cuisine: "Atlanta/Georgia",
    dishType: "drink",
    price: 7,
    image: "/images/drinks_photos/coca-cola-original-12oz.jpg",
  },

  {
    title: "Sparkling Water",
    ingredients: "Not Available",
    cuisine: "England",
    dishType: "drink",
    price: 4,
    image: "/images/drinks_photos/Sparkling_Water.jpg",
  },

  {
    title: "Baklava",
    ingredients: [
      "Phyllo Dough",
      "Sugar",
      "Walnut",
      "Cinnamon",
      "Eggs",
      "Water",
      "Lemon",
    ],
    cuisine: "Turkey",
    dishType: "dessert",
    price: 19,
    image: "/images/dessert_photos/baklava.jpg",
  },
  {
    title: "Black Tea",
    ingredients: "Tea",
    cuisine: "China",
    dishType: "drink",
    price: 5,
    image: "/images/drinks_photos/black_tea.jpg",
  },

  {
    title: "Chamomile Tea",
    ingredients: "Chamomile",
    cuisine: "Egypt",
    dishType: "drink",
    price: 5,
    image: "/images/drinks_photos/chamomile_tea.jpg",
  },
  {
    title: "Americano Coffee",
    ingredients: "Coffee",
    cuisine: "Italy",
    dishType: "drink",
    price: 5,
    image: "/images/drinks_photos/americano_coffee.jpg",
  },
  {
    title: "Latte Coffee",
    ingredients: "Coffee and Milk",
    cuisine: "Italy",
    dishType: "drink",
    price: 5,
    image: "/images/drinks_photos/latte_coffee.jpg",
  },

  {
    title: "Bean Salad",
    ingredients: [
      "Onion",
      "Green Pepper",
      "Celery",
      "Olive Oil",
      "Beans",
      "Parsley",
      "Salt",
      "Red Wine Vinegar",
    ],
    cuisine: "The United Kingdom",
    dishType: "salad",
    price: 14,
    image: "/images/salad_photos/bean_salad.jpg",
  },
  {
    title: "Caesar Salad",
    ingredients: [
      "Parmesan",
      "Crouton",
      "Lemon",
      "Romaine Lettuce",
      "Black Pepper",
      "Dijon Mustard",
      "Garlic",
      "Egg",
    ],
    cuisine: "Mexico",
    dishType: "salad",
    price: 14,
    image: "/images/salad_photos/caesar_salad.jpg",
  },
  {
    title: "Cobb Salad",
    ingredients: [
      "Avocado",
      "Blue cheese",
      "Bacon",
      "Boiled egg",
      "Black Pepper",
      "Chicken",
      "Tomatoes",
      "Chives",
    ],
    cuisine: "California",
    dishType: "salad",
    price: 14,
    image: "/images/salad_photos/cobb_salad.jpg",
  },
  {
    title: "Four Seasons Salad",
    ingredients: [
      "Balsamic Vinegar",
      "Olive Oil",
      "Dried Oragano",
      "Red Pepper Flakes",
      "Black Pepper",
      "Lettuce",
      "Pound Mushrooms",
      "Fresh Basil",
    ],
    cuisine: "Chinese",
    dishType: "salad",
    price: 14,
    image: "/images/salad_photos/four_seasons_salad.jpg",
  },
];

module.exports = dishes;
